version: '3.7'

services:
  nginx-rtmp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./files/ig_text.txt:/home/ig_text.txt
      - ./files/ig_overlay.png:/home/ig_overlay.png
      - ./files/hiragino-mincho-pro-w3.otf:/home/hiragino-mincho-pro-w3.otf

    ports:
      - 1935:1935
    depends_on: 
      - stunnel
  stunnel:
    build: 
      context: .
      dockerfile: Dockerfile-stunnel
